%Purpose: This function serves to provide information about the different types of
%eczema and save space within the main code. 
%Contributors: Isha Verma
%Last updated: April 14th, 2021
function treat = furtherSteps(diagnosis)
D = diagnosis;
if D == "neuro"
    treat = "Potential diagnosis: Neurodermatitis \n\nCommon Locations: arms, legs, back of neck, scalp, soles of feet, palms, genitals \n\nSigns and symptoms: \n     thick, leathery, scaly patches \n     darkened color: red, brown gray \n     pronounced skin lines \n\nDescription: Neurodermatitis is a common type of eczema with itchy patches of skin that become itchy and thickened, \n     and can often become discolored. This type of eczema can be triggered by things like tight clothing, \n     dry skin, and nerve injury. \n\nTreatment: To treat neurodermatitis, a doctor will often prescribe ointments such as corticosteroids. If the eczema is \n     advanced, it may need to be injected in. Furthermore, doctors may provide you with a numbing agent or oral medication \n      to reduce anxiety and itching, as left unchecked, they will often worsen neurodermatitis. \n\nSource: https://nationaleczema.org/eczema/types-of-eczema/neurodermatitis/";
elseif D == "stasis"
    treat = "Potential diagnosis: Stasis Dermatitis \n\nCommon Locations: feet and lower legs \n\nSigns and symptoms: \n     swelling \n     oozing \n     heavy or achy feeling after long periods of standing \n     rednesss or purple/ashen skin\n     orange-brown speckles of discoloration \n\nDescription: Stasis dermatitis happens due to poor circulation in your lower legs and the water and blood cells pool there. \n     It is associated with swelling and discoloration. Open sores can also form, and eventually cause your skin to be \n     thickened and bumpy. These open sores can become infected, which is why it is essential that this be treated early. \n\nTreatment: To treat stasis dermatitis, physicians will focus on reducing swelling and improving circulation. This includes \n     elevating legs, compression socks, and vitamin C. If the dermatitis has progressed to change the skin, a doctor may prescribe steroids or antibiotics as needed. \n\nSource: https://nationaleczema.org/eczema/types-of-eczema/stasis-dermatitis/";
elseif D == "atopic"
    treat = "Potential diagnosis: Atopic Dermatitis \n\nCommon Locations: elbows, knees, hands, feet, eyelids \n\nSigns and symptoms: \n     dry/scaly patches \n     redness and inflammation \n     swollen skin \n     weeping wounds \n\nDescription: Atopic dermatitis is a common type of eczema that can come and go throughout your lifetime. While the exact cause for this type of eczema is unknown, \n     it is thought to be related to a gene that controls the production of filaggrin, a protein that creates the skin surface barrier. Those with atopic \n     dermatitis will typically have dry skin in addition to the symptoms listed above. \n\nTreatment: General treatment for atopic dermatitis includes eating well, sleeping sufficiently, managing stress, and moisturizing routinely.  \n     For more severe eczema, a healthcare professional may prescribe different ointments such as corticosteroids. \n\nSource: https://nationaleczema.org/eczema/types-of-eczema/atopic-dermatitis/";
elseif D == "contact"
    treat = "Potential diagnosis: Contact Dermatitis \n\nSigns and symptoms: \n     blistering of skin \n     redness \n\nDescription: When coming into contact with a substance causes an inflammatory response, it is called contact dermatitis. \n     One substance that can cause this is an irritant, which is when something like a detergent or nickel irritates \n     the skin. The other is when contact dermatitis is due to an allergic response to a substance like poison ivy. \n\n Treatment: With contact dermatitis, it is essential to find the irritant or allergen to prevent further dermatitis. If \n     contact dermatitis is due to an allergen, a medical provider will often patch test to confirm the allergen. It is advised\n      that you do not patch test on your own. A doctor may prescribe a steroid ointment if the severity of the dermatitis indicates it. \n\nSource: https://nationaleczema.org/eczema/types-of-eczema/contact-dermatitis/";
elseif D == "seb"
    treat = "Potential diagnosis: Seborrheic Dermatisis \n\nCommon Locations: scalp, face, sides of nose, eyebrows, ears, eyelids \n\nSigns and symptoms: \n     greasy looking flakes \n     red skin \n\nDescription: Seborrheic dermatitis is a chronic type of eczema in infants and adults. It is associated with greasy flakes. \n     Thought to be an inflammatory reaction to extra Malassezia yeast. It can be triggered by medications, hormonal changes, \n     illness, stress, cold and dry weather, and harsh chemicals. \n\nTreatment: A skincare routine with gentle cleansers and moisturizers is helpful in managing seborrheic dermatitis. If necessary, a physician may prescribe \n     antifungal creams, medicated shampoos, or corticosteroid ointments. \n\nSimilar conditions: Dandruff, Psoriasis \n\nSource: https://nationaleczema.org/eczema/types-of-eczema/seborrheic-dermatitis/";
elseif D == "dys"
    treat = "Potential diagnosis: Dyshidrotic Dermatitis \n\nCommon locations: hands, soles of feet, edges of fingers and toes \n\nSigns and symptoms: \n     small fluid-filled bumps \n     itching \n\nDescription: Dyshidrotic eczema is a type of eczema with small, itchy blisters. The exact cause is not known, \n     but it can be triggered by seasonal allergies, stress, metals, and sweaty palms or frequently wetting your hands. \n     This type of eczema is also known as pompholyx eczema. \n\nTreatment: Treating this type of eczema can consist of a skincare routine with a gentle, scent-free cleanser \n     and then moisturizer. Furthermore, a doctor may prescribe medications such as corticosteroids, anti-fungals, or calcineurin inhibitors. \n\nSource: https://nationaleczema.org/eczema/types-of-eczema/dyshidrotic-eczema/";
elseif D == "num"
    treat = "Potential diagnosis: Nummular Eczema \n\nCommon Locations: arms, legs, torso, hands \n\nSigns and symptoms: \n     coin shaped lesions/paches \n\nDescription: Nummular eczema is when you have circular, itchy patches on your skin. It is also known as discoid \n     eczema and nummular dermatitis. It can be triggered by dry skin and insect bites, scrapes, chemical burns. \n     Nummular eczema can often be secondary to another type of eczema, such as stasis eczema if it is present on your legs.  \n\nTreatment: To confirm that it is nummular eczema, doctors will often scrape the skin. Treatment involves \n     corticosteroids and antibiotics prescribed by a healthcare professional. \nSimilar conditions: ringworm \n\nSource: https://nationaleczema.org/eczema/types-of-eczema/nummular-eczema/";
else
    treat = "";
end
%return treat;
end